# ur_arm:
ur_arm:
  kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
  solve_type: Speed                         # o Manipulation1, Manipulation2m Manipulation3
  kinematics_solver_timeout: 0.1            # Timeout per call
  max_iterations: 100
  position_ow_tolerance: 0.0001             # 0.1 mm
  orientation_ow_tolerance: 0.001           # ~0.06 deg