/*
--- PHYSICAL WIRING SUMMARY ---
D07 (PORTH6)          -> STEP  (driver PUL+), generated by Timer3 ISRs
D04 (PH3)             -> DIR   (driver DIR+, via Modbus coil 4)
D05 (PORTH4)          -> ENA   (driver ENBL+, active LOW)
R8                    -> Power relay (driver supply)
DI0                   -> NC limit switch input on CONTROLLINO MAXI
                         Wiring: +24V -> NC switch -> DI0
                         Normal state: HIGH, tripped/open: LOW
D00..D03              -> General outputs (via Modbus coils 0..3)

--- RAM EXTRUDER NOTES ---
- This variant keeps the same Modbus contract and pin naming used by ROS.
- STEP is still driven by Timer3 and queued through steps_accum.
- The limit switch is debounced in software (10 ms).
- When the limit switch trips, the controller:
    1) forces DIR away from the switch,
    2) backs off 4 mm,
    3) marks that backed-off pose as soft position 0,
    4) enforces a 305 mm software travel window from that zero.

--- MODBUS MAP (UNCHANGED) ---
Coils:
  0..4  -> D00..D04 (digital outputs, DIR is D04 via coil 4)
  10    -> EXTRUDE_MAN (manual extrusion enable)
  11    -> PRG_STATE   (program running state)
  12    -> EXTRUDE_PRG (program-controlled extrusion)
  13    -> QUEUE_PUSH  (rising edge enqueues HR3|HR4 as 32-bit steps)
  14    -> CANCEL_ALL  (cancel current job and clear queue)
Holding Registers:
  HR1   -> step_rate_hz
  HR2   -> cfsMultiplier (%) for legacy Timer4 path (still unused)
  HR3   -> steps_lo
  HR4   -> steps_hi
Input Registers:
  IR0   -> steps_accum low 16 bits
  IR1   -> steps_accum high 16 bits
*/

#include <Controllino.h>
#include <SPI.h>
#include <Ethernet.h>
#include <ArduinoModbus.h>

#define NUMBER_INPUTS_COILS 16
#define NUMBER_IN_HOLD_REGISTERS 16

byte mac[] = { 0xDE, 0xAD, 0xBE, 0xEF, 0xFE, 0xED };
IPAddress ip(192, 168, 1, 10);
EthernetServer ethernetServer(502);
ModbusTCPServer modbusTCPServer;

unsigned long lastExtrude = 0;

void setup() {
  pinMode(CONTROLLINO_D6, OUTPUT);   // PH5
  pinMode(CONTROLLINO_D7, OUTPUT);   // PH6
  pinMode(CONTROLLINO_DI0, INPUT);   // Limit switch input (24V digital input)

  Serial.begin(9600);

  setupTimer3();
  setTimer3Freq(1);
  setupTimer4();
  setTimer4Freq(1);

  setupLimitSwitch();
  setupModbus();

  // Preserve the legacy ROS path where print control only updates coil 10 and HR1.
  modbusTCPServer.coilWrite(4, HIGH);
  digitalWrite(CONTROLLINO_D4, HIGH);

  PORTH |= (1 << 4); // ENA HIGH -> driver disabled on boot
}

void loop() {
  EthernetClient client = ethernetServer.available();

  if (!client) {
    return;
  }

  Serial.println("new client");
  stepperDriverOn();
  modbusTCPServer.accept(client);

  while (client.connected()) {
    modbusTCPServer.poll();
    syncModbus(&lastExtrude);
  }

  Serial.println("client disconnected");
  cancelAllMotion(true);
  delay(500);
  stepperDriverOff();
}
