# Request
bool use_latest
string session_path
string field_state_path
string[] scan_mesh_paths
string output_dir
string candidate_mode
int32 beads_per_step
float64 bead_separation_mm
float64 bead_height_mm
bool orient_with_tangent
float64 tangent_sign
bool clamp_to_cone
float64 cone_max_tilt_deg
float64 base_to_world_yaw_deg
float64 target_zx
float64 target_zy
float64 target_zz
float64 target_position_scale
---
# Response
bool success
string message
string session_dir
string resolved_field_state_path
string resolved_scan_mesh_path
string cycle_output_dir
string debug_field_ply_path
string debug_contour_ply_path
string debug_candidates_ply_path
string targets_yaml_path
int32 scan_mesh_count
int32 viable_count
int32 contour_segment_count
int32 candidate_count
float64 clearance_used
float64 iso_level_used
int32 beads_per_step_used
float64 bead_separation_mm_used
float64 bead_height_mm_used
