# Request
string group_name
string eef_link
string pipeline_id
string planner_id
string named_target
geometry_msgs/PoseStamped target
float64 velocity_scale
float64 accel_scale
bool preview_only
---
# Response
bool success
int32 moveit_error_code
float64 total_time_sec
float64 path_length
geometry_msgs/PoseStamped final_pose
moveit_msgs/RobotTrajectory trajectory
