# Single TF using RPY
static_transforms:
  - parent: ur20_tool0
    child: femto__base_link
    #Put your measured mount here (meters & radians)
    xyz: [0.240, 0.000, 0.000]
    rpy: [0.000, 0.000, 0.000]

# --- OR (reference) ---
# Multiple TFs
# static_tfs:
#   - parent_frame: ur20_tool0
#     child_frame: femto__ir_optical_frame_calib
#     xyz: [-0.20, 0.0, 0.0]
#     rpy: [0.0, 0.0, 0.0]
#   - parent_frame: femto__ir_optical_frame_calib
#     child_frame: femto__depth_optical_frame_calib
#     xyz: [0.0, 0.0, 0.0]
#     quat: [0.0, 0.0, 0.0, 1.0]
