# ur_arm:
#   kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
#   kinematics_solver_search_resolution: 0.0050000000000000001
#   kinematics_solver_timeout: 0.0050000000000000001
ur_arm:
  kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
  solve_type: Speed                # o Manipulation1, Manipulation2m Manipulation3
  kinematics_solver_timeout: 0.1       # Timeout per call
  max_iterations: 100                 #
  position_ow_tolerance: 0.001           # 1 mm
  orientation_ow_tolerance: 0.1        # 