# Limits for the Pilz planner
cartesian_limits:
  max_trans_vel: 1.0
  max_trans_acc: 2.25
  max_trans_dec: -5.0
  max_rot_vel: 1.57
  
planning_volume:
    min_corner: [-2.0, -0.25, 0.0]
    max_corner: [ 2.0,  2.0, 2.0]